Repository convex-optimization-for-all/convex-optimization-for-all.github.io, pull requests merged in 2021-03, with the labels that each got.

#26 Add docker-compose option for local hosting
  contribution/_posts/21-01-27-how_to_contribute.md
  contribution/_posts/21-01-27-initial_settings.md
  docker-compose.yml
Labels: documentation, enhancement

#31 구글 애널리틱스 붙이기
  _config.yml
Labels: enhancement

#29 Fix latex issue(\vert) on Chapter01
  chapter01/_posts/21-01-28-convex_optimization_problem.md
  chapter01/_posts/21-01-28-goals_and_topics.md
Labels: invalid

#40 Initialize CODEOWNERS system
  CODEOWNERS
Labels: enhancement

#27 Update Github Conventions
  contribution/_posts/21-02-03-conventions.md
Labels: documentation

#37 Update contents list on README as Markdown Table
  README.md
Labels: documentation

#56 Add comments using utterance
  .github/workflows/closed_issue.yml
  _layouts/post.html
  src/change_issue_title.py
  src/requirements.txt
Labels: enhancement

#60 Change title splitter
  src/change_issue_title.py
Labels: bug

#57 chapter07 Subgradient Migration
  chapter07/_posts/20-01-08-test.md
  chapter07/_posts/21-03-25-07_00_subgradient.md
  chapter07/_posts/21-03-25-07_01_subgradient.md
  chapter07/_posts/21-03-25-07_02_01_connection_to_a_convexity_geometry.md
  chapter07/_posts/21-03-25-07_02_02_subgradient_calculus.md
  chapter07/_posts/21-03-25-07_02_subdifferentials.md
  chapter07/_posts/21-03-25-07_03_01_subgradient_optimality_condition.md
  chapter07/_posts/21-03-25-07_03_02_derivation_of_first-order_optimality_condition.md
  chapter07/_posts/21-03-25-07_03_03_example_lasso_optimality_condition.md
  chapter07/_posts/21-03-25-07_03_04_example_soft-thresholding.md
  chapter07/_posts/21-03-25-07_03_05_example_distance_to_convex_set.md
  chapter07/_posts/21-03-25-07_03_subgradient_optimality_condition.md
Labels: Migration
