Repository convex-optimization-for-all/convex-optimization-for-all.github.io, pull requests merged in 2021-05, with the labels that each got.

#81 Chapter 13 Migration
  chapter13/_posts/20-01-08-test.md
  chapter13/_posts/21-04-05-13_01_Uses_of_duality.md
  chapter13/_posts/21-04-05-13_02_Solving_the_primal_via_the_dual.md
  chapter13/_posts/21-04-05-13_03_Dual_norms.md
  chapter13/_posts/21-04-05-13_04_01_Example_lasso_dual.md
  chapter13/_posts/21-04-05-13_04_02_Conjugates_and_dual_problems.md
  chapter13/_posts/21-04-05-13_04_03_Shifting_linear_transformations.md
  chapter13/_posts/21-04-05-13_04_Conjugate_function.md
  chapter13/_posts/21-04-05-13_05_Dual_cones.md
  chapter13/_posts/21-04-05-13_06_Dual_subtleties_Double_dual.md
  chapter13/_posts/21-04-05-13_Duality_uses_and_correspondences.md
Labels: Migration

#76 Chapter 12 migration
  chapter12/_posts/20-01-08-test.md
  chapter12/_posts/21-04-02-12_01_Karush_Kuhn_Tucker_conditions.md
  chapter12/_posts/21-04-02-12_02_Example_quadratic_with_equality_constraints.md
  chapter12/_posts/21-04-02-12_03_Example_water_filling.md
  chapter12/_posts/21-04-02-12_04_Example_support_vector_machines.md
  chapter12/_posts/21-04-02-12_05_Constrained_and_Lagrange_forms.md
  chapter12/_posts/21-04-02-12_06_Uniqueness_in_L1_penalized_problems.md
  chapter12/_posts/21-04-02-12_KKT_conditions.md
Labels: Migration

#85 Update main page contents
  README.md
  home/_posts/21-01-20-contents.html
  home/_posts/21-01-20-contents.md
  home/_posts/21-02-03-makers.md
Labels: enhancement

#97 fix post url warning msg
  chapter09/_posts/20-01-08-09_02_convergence_analysis.md
  chapter09/_posts/20-01-08-09_05_03_example_FISTA.md
Labels: bug

#72 Migration chapter15
  chapter15/_posts/20-01-08-test.md
  chapter15/_posts/21-03-28-15_01_01_inequality_constrained_minimization_problems.md
  chapter15/_posts/21-03-28-15_01_02_log_barrier_function_and_barrier_method.md
  chapter15/_posts/21-03-28-15_01_03_log_barrier_calculus.md
  chapter15/_posts/21-03-28-15_01_barrier_method_and_log_barrier_function.md
  chapter15/_posts/21-03-28-15_02_central_path.md
  chapter15/_posts/21-03-28-15_03_01_perturbed_kkt_conditions.md
  chapter15/_posts/21-03-28-15_03_02_suboptimality_gap.md
  chapter15/_posts/21-03-28-15_03_properties_and_interpretation.md
  chapter15/_posts/21-03-28-15_04_barrier_method_v0_and_v1.md
  chapter15/_posts/21-03-28-15_05_convergence_analysis.md
  chapter15/_posts/21-03-28-15_06_barrier_method_v2.md
  chapter15/_posts/21-03-28-15_07_feasibility_methods.md
  chapter15/_posts/21-03-28-15_08_formal_barrier_method.md
  chapter15/_posts/21-03-28-15_barrier_method.md
Labels: Migration

#101 [HotFix] Fix markdown table
  README.md
Labels: bug

#95 chapter17 migration
  chapter17/_posts/20-01-08-test.md
  chapter17/_posts/21-05-01-17_01_barrier_method_duality_optimality_revisited.md
  chapter17/_posts/21-05-01-17_02_01_central_path_equations_and_newton_step.md
  chapter17/_posts/21-05-01-17_02_02_surrogate_duality_gap_residuals.md
  chapter17/_posts/21-05-01-17_02_03_primal_dual_algorithm.md
  chapter17/_posts/21-05-01-17_02_primal_dual_interior_point_method.md
  chapter17/_posts/21-05-01-17_03_some_history.md
  chapter17/_posts/21-05-01-17_04_special_case_linear_programming.md
  chapter17/_posts/21-05-01-17_05_optimality_conditions_for_semidefinite_programming.md
  chapter17/_posts/21-05-01-17_primal_dual_interior_point_method.md
Labels: Migration

#74 Add chapter 16 posts
  chapter16/_posts/20-01-08-test.md
  chapter16/_posts/21-03-31-16_01_lagrangian_duality_revisited.md
  chapter16/_posts/21-03-31-16_02_optimality_conditions.md
  chapter16/_posts/21-03-31-16_03_fenchel_duality.md
  chapter16/_posts/21-03-31-16_duality_revisited.md
Labels: Migration

#108 Update wikidocs link to post_url
  chapter03/_posts/21-02-12-03_06_convexity_with_respect_to_generalized_inequalities.md
  chapter04/_posts/20-02-08-04_04_Partial_optimization.md
  chapter06/_posts/21-03-20-06_03_01_convergence_analysis_and_proof.md
  chapter06/_posts/21-03-20-06_03_04_convergence_analysis_under_strong_convexity.md
  chapter08/_posts/20-03-29-08_01_03_convergence_analysis.md
  chapter08/_posts/20-03-29-08_01_04_convergence_rate.md
  chapter14/_posts/2021-03-26-14_01_01_newton_method_interpretation.md
  chapter14/_posts/2021-03-26-14_01_newton_method.md
  chapter14/_posts/2021-03-26-14_02_03_local_convergence_analysis.md
  chapter14/_posts/2021-03-26-14_05_convergence_analysis.md
  chapter14/_posts/2021-03-26-14_08_special_cases.md
  chapter14/_posts/2021-03-26-14_09_quasi_newton_methods.md
  chapter17/_posts/21-05-01-17_01_barrier_method_duality_optimality_revisited.md
  chapter17/_posts/21-05-01-17_02_02_surrogate_duality_gap_residuals.md
  chapter19/_posts/21-03-24-19_01_01_Reminder:_proximal_gradient_descent.md
  chapter19/_posts/21-03-24-19_02_Backtracking_line_search.md
  chapter21/_posts/21-03-29-21_00_Alternating_Direction_Method_of_Multipliers.md
  chapter21/_posts/21-03-29-21_01_Last_time_Dual_method,_Augmented_Lagrangian_method,_ADMM,_ADMM_in_scaled_form.md
  chapter21/_posts/21-03-29-21_02_Connection_to_proximal_operators.md
  chapter21/_posts/21-03-29-21_03_Example_:_Lasso_regression_and_group_lasso_Regression.md
  chapter21/_posts/21-03-29-21_05_Consensus_ADMM.md
  chapter21/_posts/21-03-29-21_06_Faster_convergence_with_subprogram_parametrization_:_example_of_the_2d_fused_lasso_problem.md
  chapter22/_posts/21-03-28-22_02_Conditional_gradient_method.md
  chapter23/_posts/21-03-28-23_01_Coordinate_descent.md
  chapter23/_posts/21-03-28-23_02_Example_linear_regression.md
  chapter23/_posts/21-03-28-23_03_Example_lasso_regression.md
  chapter23/_posts/21-03-28-23_04_Example_pathwise_coordinate.md
Labels: Migration

#112 Fix video url on README
  README.md
Labels: bug

#114 Fix numbering issue on How to Contribute
  contribution/_posts/21-01-27-how_to_contribute.md
Labels: bug

#115 Fix contents on main page
  home/_posts/21-01-20-contents.md
Labels: bug

#117 Fix typos - `ch24-01` & `how to contribute`
  chapter24/_posts/21-03-28-24_01_Definition.md
  contribution/_posts/21-01-27-how_to_contribute.md
  contribution/_posts/21-02-03-conventions.md
Labels: bug

#131 chapter05: Fix url
  chapter05/_posts/21-02-08-05_01_Linear_Programming_(LP).md
Labels: bug

#148 [chapter11 typo] Change plus sign to minus
  contents/chapter11/_posts/21-03-24-11_02_Lagrange_dual_function.md
Labels: typo
