Repository convex-optimization-for-all/convex-optimization-for-all.github.io, pull requests merged in 2021-06, with the labels that each got.

#157 fix typo
  contents/chapter17/_posts/21-05-01-17_primal_dual_interior_point_method.md
Labels: bug

#158 Add scorllbar padding for readability
  _includes/head.html
Labels: enhancement

#156 image migration for chapter17-chapter20
  contents/chapter17/_posts/21-05-01-17_04_special_case_linear_programming.md
  contents/chapter18/_posts/21-03-23-18_01_Secant_Equation_and_Curvature_Condition.md
  contents/chapter18/_posts/21-03-23-18_07_Limited_Memory_BFGS_(LBFGS).md
  contents/chapter19/_posts/21-03-24-19_01_01_Reminder:_proximal_gradient_descent.md
  contents/chapter19/_posts/21-03-24-19_01_03_Scaled_proximal_map.md
  contents/chapter19/_posts/21-03-24-19_05_Notable_examples.md
  contents/chapter20/_posts/21-03-27-20_02_01_Dual_Decomposition_with_Equality_Constraint.md
  img/chapter_img/chapter17/barrier_vs_primal_dual.png
  img/chapter_img/chapter17/barrier_vs_primal_dual2.png
  img/chapter_img/chapter18/algorithm_quasi-newton.png
  img/chapter_img/chapter18/intuition_of_secant_eq.png
  img/chapter_img/chapter19/09.01_01_proximal_gradient_descent.png
  img/chapter_img/chapter19/09.01_03_projection_operator.png
  img/chapter_img/chapter19/09.05_Inexact_prox.png
  img/chapter_img/chapter19/09.05_Lasso_Example-sparse.png
  img/chapter_img/chapter19/09.05_Lasso_Example1.png
  img/chapter_img/chapter20/decomposition.png
Labels: Migration, enhancement

#166 Migrate images and align math formula (ch21~24)
  contents/chapter21/_posts/21-03-29-21_01_Last_time_Dual_method,_Augmented_Lagrangian_method,_ADMM,_ADMM_in_scaled_form.md
  contents/chapter21/_posts/21-03-29-21_03_Example_:_Lasso_regression_and_group_lasso_Regression.md
  contents/chapter21/_posts/21-03-29-21_04_Example_:_Sparse_subspace_estimation_and_sparse_plus_low_rank_decomposition.md
  contents/chapter21/_posts/21-03-29-21_05_Consensus_ADMM.md
  contents/chapter21/_posts/21-03-29-21_06_Faster_convergence_with_subprogram_parametrization_:_example_of_the_2d_fused_lasso_problem.md
  contents/chapter22/_posts/21-03-28-22_01_Last_time_ADMM.md
  contents/chapter22/_posts/21-03-28-22_02_Conditional_gradient_method.md
  contents/chapter22/_posts/21-03-28-22_04_Properties_and_variants.md
  contents/chapter23/_posts/21-03-28-23_01_Coordinate_descent.md
  contents/chapter23/_posts/21-03-28-23_02_Example_linear_regression.md
  contents/chapter23/_posts/21-03-28-23_03_Example_lasso_regression.md
  contents/chapter24/_posts/21-03-28-24_01_Definition.md
  contents/chapter24/_posts/21-03-28-24_02_Example_of_integer_programs.md
  contents/chapter24/_posts/21-03-28-24_04_Relaxations.md
  contents/chapter24/_posts/21-03-28-24_05_Branch_and_bound_algorithm.md
  img/chapter_img/chapter21/2dfussed.png
  img/chapter_img/chapter21/2dfussedlasso.png
  img/chapter_img/chapter21/admm_iteration_visualized.png
  img/chapter_img/chapter21/candes.png
  img/chapter_img/chapter21/lasso.png
  img/chapter_img/chapter21/ll1.png
  img/chapter_img/chapter21/ll2.png
  img/chapter_img/chapter22/away_steps.png
  img/chapter_img/chapter22/comparing_projected_and_conditional_gradient.png
  img/chapter_img/chapter22/frank_wolfe.png
  img/chapter_img/chapter23/gd_vs_agd_vs_cd.png
  img/chapter_img/chapter23/non-smooth_function.png
  img/chapter_img/chapter23/pd_vs_agd_vs_cd.png
  img/chapter_img/chapter23/separable_non-smooth.png
  img/chapter_img/chapter23/smooth_function.png
Labels: enhancement

#171 Remove unnecessary hyperlink in main page
  home/_posts/21-02-03-makers.md
Labels: bug

#162 Align formula for 18 chapter
  contents/chapter18/_posts/21-03-23-18_03_Davidon_Fletcher_Powell_(DFP)_Update.md
  contents/chapter18/_posts/21-03-23-18_04_Broyden_Fletcher_Goldfarb_Shanno_(BFGS)_update.md
  contents/chapter18/_posts/21-03-23-18_07_Limited_Memory_BFGS_(LBFGS).md
Labels: enhancement

#161 align formula on 17 chapter
  contents/chapter17/_posts/21-05-01-17_01_barrier_method_duality_optimality_revisited.md
Labels: enhancement

#173 ch-12-06 Align 변경
  contents/chapter12/_posts/21-04-02-12_06_Uniqueness_in_L1_penalized_problems.md
Labels: enhancement
