Repository convex-optimization-for-all/convex-optimization-for-all.github.io, pull requests merged in 2021-04, with the labels that each got.

#61 Fix related posts system
  _layouts/post.html
Labels: enhancement

#42 Chapter06 Gradient Descent Migration
  chapter06/_posts/20-01-08-test.md
  chapter06/_posts/21-03-20-06_00_gradient_descent.md
  chapter06/_posts/21-03-20-06_01_gradient_descent.md
  chapter06/_posts/21-03-20-06_02_01_fixed_step_size.md
  chapter06/_posts/21-03-20-06_02_02_backtracking_line_search.md
  chapter06/_posts/21-03-20-06_02_03_exact_line_search.md
  chapter06/_posts/21-03-20-06_02_how_to_choose_step_sizes.md
  chapter06/_posts/21-03-20-06_03_01_convergence_analysis_and_proof.md
  chapter06/_posts/21-03-20-06_03_02_convex_function_quardratic_upper_bound.md
  chapter06/_posts/21-03-20-06_03_03_convergence analysis_for_backtracking.md
  chapter06/_posts/21-03-20-06_03_04_convergence_analysis_under_strong_convexity.md
  chapter06/_posts/21-03-20-06_03_05_look_at_the_conditions_and_practicalities.md
  chapter06/_posts/21-03-20-06_03_06_can_we_do_better.md
  chapter06/_posts/21-03-20-06_03_convergence_analysis.md
  chapter06/_posts/21-03-20-06_04_gradient_boosting.md
  chapter06/_posts/21-03-20-06_05_stochastic_gradient_descent.md
Labels: Migration

#78 Add hyperlink convention
  contribution/_posts/21-02-03-conventions.md
Labels: documentation

#82 Change logo
  _includes/head.html
  public/apple-touch-icon-precomposed.png
  public/convex-logo-144x144.png
  public/favicon.ico
  public/logo.png
Labels: enhancement

#52 10 Chapter migration
  chapter10/_posts/20-01-08-test.md
  chapter10/_posts/21-03-22-10_01_Lower_Bounds_in_Linear_Programs.md
  chapter10/_posts/21-03-22-10_02_Duality_in_general_LPs.md
  chapter10/_posts/21-03-22-10_03_Max_flow_and_min_cut.md
  chapter10/_posts/21-03-22-10_04_Another_Perspective_on_LP_duality.md
  chapter10/_posts/21-03-22-10_05_Matrix_Games.md
  chapter10/_posts/21-03-22-10_Duality_in_Linear_Programs.md
Labels: Approved, Migration

#54 11 Chapter Migration
  chapter11/_posts/20-01-08-test.md
  chapter11/_posts/21-03-24-11_1_Lagrangian.md
  chapter11/_posts/21-03-24-11_2_Lagrange_dual_function.md
  chapter11/_posts/21-03-24-11_3_Lagrange_dual_problem.md
  chapter11/_posts/21-03-24-11_4_Strong_duality.md
  chapter11/_posts/21-03-24-11_5_Duality_gap.md
  chapter11/_posts/21-03-24-11_Duality_in_General_Programs.md
Labels: Approved, Migration

#77 Chapter09 Proximal Gradient Descent Migration
  chapter06/_posts/21-03-20-06_03_03_convergence analysis_for_backtracking.md
  chapter09/_posts/20-01-08-09_01_proximal_gradient_descent.md
  chapter09/_posts/20-01-08-09_02_convergence_analysis.md
  chapter09/_posts/20-01-08-09_03_example_matrix_completion.md
  chapter09/_posts/20-01-08-09_04_special_cases.md
  chapter09/_posts/20-01-08-09_05_01_accelerated_proximal_gradient_method.md
  chapter09/_posts/20-01-08-09_05_02_convergence_analysis.md
  chapter09/_posts/20-01-08-09_05_03_example_FISTA.md
  chapter09/_posts/20-01-08-09_05_04_is_acceleration_always_useful?.md
  chapter09/_posts/20-01-08-09_05_acceleration.md
  chapter09/_posts/20-01-08-09_proximal_gradient_descent_and_acceleration.md
  chapter09/_posts/20-01-08-test.md
Labels: Migration

#53 Chapter 18 Quasi Newton methods Migration
  chapter18/_posts/20-01-08-test.md
  chapter18/_posts/21-03-23-18_00_Quasi_Newton_methods.md
  chapter18/_posts/21-03-23-18_01_Secant_Equation_and_Curvature_Condition.md
  chapter18/_posts/21-03-23-18_02_Symmetric_Rank_One_Update_(SR1).md
  chapter18/_posts/21-03-23-18_03_Davidon_Fletcher_Powell_(DFP)_Update.md
  chapter18/_posts/21-03-23-18_04_Broyden_Fletcher_Goldfarb_Shanno_(BFGS)_update.md
  chapter18/_posts/21-03-23-18_05_The_Broyden_Class.md
  chapter18/_posts/21-03-23-18_06_Superlinear_convergence.md
  chapter18/_posts/21-03-23-18_07_Limited_Memory_BFGS_(LBFGS).md
Labels: Migration

#55 Chapter19 Proximal Netwon Method Migration
  chapter19/_posts/20-01-08-test.md
  chapter19/_posts/21-03-24-19_00_Proximal_Newton_Method.md
  chapter19/_posts/21-03-24-19_01_00_Proximal_Newton_method.md
  chapter19/_posts/21-03-24-19_01_01_Reminder:_proximal_gradient_descent.md
  chapter19/_posts/21-03-24-19_01_02_Proximal_Newton_method.md
  chapter19/_posts/21-03-24-19_01_03_Scaled_proximal_map.md
  chapter19/_posts/21-03-24-19_02_Backtracking_line_search.md
  chapter19/_posts/21-03-24-19_03_When_would_we_use_proximal_Newton?.md
  chapter19/_posts/21-03-24-19_04_Convergence_analysis.md
  chapter19/_posts/21-03-24-19_05_Notable_examples.md
  chapter19/_posts/21-03-24-19_06_Proximal_quasi_Newton_methods.md
  chapter19/_posts/21-03-24-19_07_Projected_Newton_method.md
Labels: Migration

#58 Fix how to show contents list on chapter page
  _layouts/page.html
  public/css/poole.css
Labels: enhancement

#63 Migration chapter14
  chapter14/_posts/20-01-08-test.md
  chapter14/_posts/2021-03-26-14_01_01_newton_method_interpretation.md
  chapter14/_posts/2021-03-26-14_01_newton_method.md
  chapter14/_posts/2021-03-26-14_02_01_root_finding.md
  chapter14/_posts/2021-03-26-14_02_02_affine_invariance_of_newton_method.md
  chapter14/_posts/2021-03-26-14_02_03_local_convergence_analysis.md
  chapter14/_posts/2021-03-26-14_02_interpretation_and_properties.md
  chapter14/_posts/2021-03-26-14_03_newton_decrement.md
  chapter14/_posts/2021-03-26-14_04_backtracking_line_search.md
  chapter14/_posts/2021-03-26-14_05_convergence_analysis.md
  chapter14/_posts/2021-03-26-14_06_01_definition_of_self_concordant_functions.md
  chapter14/_posts/2021-03-26-14_06_02_convergence_analysis_for_self_concordant_functions.md
  chapter14/_posts/2021-03-26-14_06_self_concordance.md
  chapter14/_posts/2021-03-26-14_07_comparison_to_first_order_method.md
  chapter14/_posts/2021-03-26-14_08_special_cases.md
  chapter14/_posts/2021-03-26-14_09_quasi_newton_methods.md
  chapter14/_posts/2021-03-26-14_newton_method.md
Labels: Migration

#64 chapter20 dual methods migration
  chapter20/_posts/20-01-08-test.md
  chapter20/_posts/21-03-27-20_00_Dual_Methos.md
  chapter20/_posts/21-03-27-20_01_00_Dual_(sub)gradient_methods.md
  chapter20/_posts/21-03-27-20_01_01_Convergence_Analysis.md
  chapter20/_posts/21-03-27-20_02_00_Dual_Decomposition.md
  chapter20/_posts/21-03-27-20_02_01_Dual_Decomposition_with_Equality_Constraint.md
  chapter20/_posts/21-03-27-20_02_02_Dual_Decomposition_with_Inequality_Constraint.md
  chapter20/_posts/21-03-27-20_03_Augmented_Lagrangians.md
  chapter20/_posts/21-03-27-20_04_00_A_peak_at_ADMM.md
  chapter20/_posts/21-03-27-20_04_01_ADMM.md
  chapter20/_posts/21-03-27-20_04_02_Converegence_Guarantee.md
  chapter20/_posts/21-03-27-20_04_03_ADMM_in_Scaled_Form.md
  chapter20/_posts/21-03-27-20_04_04_Example:_Alternating_Projection.md
  chapter20/_posts/21-03-27-20_05_References.md
Labels: Migration

#75 migration chapter 21
  chapter21/_posts/20-01-08-test.md
  chapter21/_posts/21-03-29-21_00_Alternating_Direction_Method_of_Multipliers.md
  chapter21/_posts/21-03-29-21_01_Last_time_Dual_method,_Augmented_Lagrangian_method,_ADMM,_ADMM_in_scaled_form.md
  chapter21/_posts/21-03-29-21_02_Connection_to_proximal_operators.md
  chapter21/_posts/21-03-29-21_03_Example_:_Lasso_regression_and_group_lasso_Regression.md
  chapter21/_posts/21-03-29-21_04_Example_:_Sparse_subspace_estimation_and_sparse_plus_low_rank_decomposition.md
  chapter21/_posts/21-03-29-21_05_Consensus_ADMM.md
  chapter21/_posts/21-03-29-21_06_Faster_convergence_with_subprogram_parametrization_:_example_of_the_2d_fused_lasso_problem.md
Labels: Migration

#84 Chapter23 - Migration
  chapter23/_posts/20-01-08-test.md
  chapter23/_posts/21-03-28-23_01_Coordinate_descent.md
  chapter23/_posts/21-03-28-23_02_Example_linear_regression.md
  chapter23/_posts/21-03-28-23_03_Example_lasso_regression.md
  chapter23/_posts/21-03-28-23_04_Example_pathwise_coordinate.md
  chapter23/_posts/21-03-28-23_Coordinate_Descent.md
Labels: Migration

#86 Chapter 24 - migration
  chapter24/_posts/20-01-08-test.md
  chapter24/_posts/21-03-28-24_01_Definition.md
  chapter24/_posts/21-03-28-24_02_Example_of_integer_programs.md
  chapter24/_posts/21-03-28-24_03_Solving_integer_programs.md
  chapter24/_posts/21-03-28-24_04_Relaxations.md
  chapter24/_posts/21-03-28-24_05_Branch_and_bound_algorithm.md
  chapter24/_posts/21-03-28-24_Mixed_integer_programming.md
Labels: Migration

#87 Chapter 25 - migration
  chapter25/_posts/20-01-08-test.md
  chapter25/_posts/21-03-28-25_01_01_Convexification.md
  chapter25/_posts/21-03-28-25_01_02_Cutting_plane_algorithm.md
  chapter25/_posts/21-03-28-25_01_03_Gomory_cuts.md
  chapter25/_posts/21-03-28-25_01_04_Branch_and_cut_algorithm.md
  chapter25/_posts/21-03-28-25_01_Cutting_planes.md
  chapter25/_posts/21-03-28-25_02_01_Best_subset_selection.md
  chapter25/_posts/21-03-28-25_02_02_Least_mean_squares.md
  chapter25/_posts/21-03-28-25_02_Two_extended_examples.md
  chapter25/_posts/21-03-28-25_Mixed_integer_programming.md
Labels: Migration

#65 Feature/chapter4
  chapter04/_posts/20-01-08-test.md
  chapter04/_posts/20-02-08-04_01_Basic_terminology.md
  chapter04/_posts/20-02-08-04_02_Convex_solution_sets.md
  chapter04/_posts/20-02-08-04_03_First_order_optimality_condition.md
  chapter04/_posts/20-02-08-04_04_Partial_optimization.md
  chapter04/_posts/20-02-08-04_05_Transformations_and_change_of_variables.md
  chapter04/_posts/20-02-08-04_06_Eliminating_equality_constraints.md
  chapter04/_posts/20-02-08-04_07_Slack_variables.md
  chapter04/_posts/20-02-08-04_08_Relaxation.md
Labels: Migration

#89 Chapter 22 - migration
  chapter22/_posts/20-01-08-test.md
  chapter22/_posts/21-03-28-22_01_Last_time_ADMM.md
  chapter22/_posts/21-03-28-22_02_Conditional_gradient_method.md
  chapter22/_posts/21-03-28-22_03_Convergence_analysis.md
  chapter22/_posts/21-03-28-22_04_Properties_and_variants.md
  chapter22/_posts/21-03-28-22_Conditional_Gradient_Method.md
Labels: Migration

#88 [Hotfix] Drop conflict msg on Chapter 06
  chapter06/_posts/21-03-20-06_01_gradient_descent.md
  chapter06/_posts/21-03-20-06_03_03_convergence analysis_for_backtracking.md
Labels: bug
